
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  port: 5432


development:
  <<: *default
  database: trackerbot_development
  username: trackerbot
  password: <%= ENV['TRACKERBOT_DB_PASSWORD'] %>


test:
  <<: *default
  database: trackerbot_test
  username: trakcerbot
  password: <%= ENV['TRACKERBOT_DB_PASSWORD'] %>


production:
  <<: *default
  database: trackerbot_production
  username: trackerbot
  password: <%= ENV['TRACKERBOT_DB_PASSWORD'] %>
